baseURL = "https://stlouisshag.com/"
languageCode = "en-us"
title = "St Louis Shag"
theme = "airspace-hugo"

# The site's parameters
[params]
    dateformat = "July 13, 2018"
    home = "Home"

    [params.slider]
    enable = true
    title = "St. Louis Shag"
    subtitle = "A swing era dance from St. Louis, Missouri"

    [params.wrapper]
    enable = true
    title = "About St. Louis Shag"
    italic = "St. Louis Shag is an up-tempo partnered swing dance that emerged in St. Louis, Missouri during the mid-1930s."
    paragraph = " The primary step is an eight-count basic done side-by-side, which is augmented by rhythmic variations using kicks, stomps, cross-overs, quick steps, and brush-steps. Skilled partners will change positions from side-by-side to open, hand-to-hand, back-to-back, and front-to-back positions, as well as break away from one another. Historically, St. Louis Shag was not a stand-alone dance, but an element of the wider Lindy Hop or jitterbug styles featuring swingouts and acrobatics. As a derivative of 1920s partnered Charleston, Shag draws from African-American dance traditions that became an increasingly key aspect of nightlife in urban areas during the early 1900s. Shag dancers value individual expression and lead and follow teamwork."
