baseURL = "https://stlouisshag.com/"
languageCode = "en-us"
title = "St Louis Shag"
theme = "airspace-hugo"

# The site's parameters
[params]
    dateformat = "July 13, 2018"
    home = "Home"

    [params.slider]
    enable = true
    title = "St. Louis Shag"
    subtitle = "A swing era dance from St. Louis, Missouri"

    [params.wrapper]
    enable = true
    title = "About St. Louis Shag"
    italic = "St. Louis Shag has a long-standing history in St. Louis, where it has remained throughout many generations."
    paragraph = "These days it is danced world-wide from Dublin, Ireland to Herräng, Sweden. This website exists to become a resource for the education, preservation, and spread of this swing-era dance."
